### ISSUE TITLE
Rename this repo?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLinearAlgebra/SuiteSparseOld.jl#11]
Now that https://github.com/JuliaLang/SuiteSparse.jl exists and is an external stdlib, should this repo be renamed to avoid confusion when Googling?

@ViralBShah @andreasnoack

**Comment by DilumAluthge** [comment]
Actually, it looks like this repo contains (roughly speaking) a three year old copy of the SuiteSparse stdlib.

Could we just delete this repo in favor of https://github.com/JuliaLang/SuiteSparse.jl? And update the General registry to point to https://github.com/JuliaLang/SuiteSparse.jl?

**Comment by ViralBShah** [comment]
I'll rename it for now.

**Comment by DilumAluthge** [comment]
Probably best to first merge https://github.com/JuliaRegistries/General/pull/36615 and make sure nothing breaks

**Comment by ViralBShah** [comment]
I am quite sure this repo was only used as an experiment to see if we could move SuiteSparse out of base, and nobody actually ever used it. In fact, I didn't even know it was registered.

**Comment by DilumAluthge** [comment]
Just to be safe, I copied the tags from this repo to the new repo.

If you compare the old tags (https://github.com/JuliaLinearAlgebra/SuiteSparseOld.jl/tags) to the new tags (https://github.com/JuliaLang/SuiteSparse.jl/tags), they are the same.

**Comment by ViralBShah** [comment]
Actually shouldn't the release tags be consistent with julia versions rather than these? Really, I don't think we should carry over these things.

**Comment by DilumAluthge** [comment]
Makes sense to me! I'll delete the tags from https://github.com/JuliaLang/SuiteSparse.jl/tags

**Comment by DilumAluthge** [comment]
Done, the tags are gone.
