### ISSUE TITLE
Converting SuiteSparse.SPQR.QRSparseQ to SparseMatrixCSC

### ISSUE THREAD

**Issue by volkerkarle** [JuliaLinearAlgebra/SuiteSparseOld.jl#8]
Hi folks,

Using sparse(F.Q) takes a very long time. Somehow sparse() is not using the correct method, which I described [here](https://stackoverflow.com/questions/63035209/converting-suitesparse-spqr-qrsparseq-to-sparsematrixcsc/63038171#63038171).
I do not know where to change this in this wrapper, maybe you can have a look. Another thing is that lmul! in spqr.jl is not optimized for sparse matrices [https://github.com/JuliaLinearAlgebra/SuiteSparse.jl/blob/4c3efa357aed9c4da8c7465bce69acf35986435f/src/spqr.jl#L201](url)
```
function LinearAlgebra.lmul!(Q::QRSparseQ, A::StridedVecOrMat)
    if size(A, 1) != size(Q, 1)
        throw(DimensionMismatch("size(Q) = $(size(Q)) but size(A) = $(size(A))"))
    end
    for l in size(Q.factors, 2):-1:1
        τl = -Q.τ[l]
        h = view(Q.factors, :, l)
        for j in 1:size(A, 2)
            a = view(A, :, j)
            LinearAlgebra.axpy!(τl*dot(h, a), h, a)
        end
    end
    return A
end
```
In particular, one has to use lmul!(Q, Matrix(A)) in order to perform the multiplication with a sparse matrix. Further, to retrieve Q, the routine in julia/qr.jl is not optimized as well 

`Matrix{T}(Q::AbstractQ{S}) where {T,S} = Matrix{T}(lmul!(Q, Matrix{S}(I, size(Q, 1), min(size(Q.factors)...))))`

You see that this is merely a multiplication with identity. Maybe there is a optimized way to retrieve Q in a sparse way? 

Thanks a lot,

v.

**Comment by DilumAluthge** [comment]
Hi,

Thank you for the issue! Can you please post this issue on this repo instead: https://github.com/JuliaLang/SuiteSparse.jl

Thank you!
